### ISSUE TITLE
heuristic.rb should use github api when possible.

### ISSUE THREAD

**Issue by Moisan** [Homebrew/homebrew-livecheck#102]
Some Github repositories have tags such as "latest release" that can be found with the github api: 
```
https://api.github.com/repos/{owner}/{repo-name}/releases/latest
```
In some case homebrew-livecheck guess is wrong because it does not take this information into account. I propose we use it when available.

Note that a couple of livecheckables already use this url instead of the guess functionality, e.g. `kotlin` and `prometheus`. This would reduce the number of livechekables needed to be accurate.

**Comment by Moisan** [comment]
So you mean that it aggregates all version from different urls, including the `master` and then order them?

**Comment by youtux** [comment]
Sorry, I got your message completely wrong. I will look into that, but I can’t promise anything so far.
Feel free to open a PR.
