### ISSUE TITLE
Support homebrew-cask

### ISSUE THREAD

**Issue by crunchtime-ali** [Homebrew/homebrew-livecheck#1084]
Has supporting https://github.com/Homebrew/homebrew-cask ever be considered or is it something you would consider accepting pull requests for?

 I couldn't find any hints on Google, all relevant repositories and the Homebrew discourse.

**Comment by SMillerDev** [comment]
I think it's a good idea and I'd love to see a pull request for it. Currently the repository is being migrated to be part of homebrew/brew though. So you might need to wait for that or prepare to rework it once the migration is done.

**Comment by crunchtime-ali** [comment]
Okay, I will follow the progress of the migration and cook up something. Since this affects the `brew` repository I will close this issue.
