### ISSUE TITLE
Make this an official Homebrew developer command

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/homebrew-livecheck#16]
How would you feel about this moving to the Homebrew organisation and this happening? It could be run basically the same (same people have permissions on the repo) but might just get it a bit more visibility.

Ideally eventually I'd love to have this running near continuously on a machine to check for updates and autosubmit PRs.

Thoughts?

CC @ilovezfs who is a maintainer I know that uses this.

**Comment by youtux** [comment]
Well, my original goal when I created this project was to have the command embedded in Homebrew and this seems to be a step in that direction, so I am totally up for it!

Potentially with more attention it could work with a lot more packages and even have less breakage if this command is going to be tested in the homebrew's CI at every merge.

On the other side I don't think the code quality of this project is up to the standard of the Homebrew organization and unfortunately I don't have much time to invest on it.

**Comment by MikeMcQuaid** [comment]
@youtux Cool! How about I add you to the Homebrew organisation which should allow you to move this repository there? GitHub will setup redirects so there won't be any issues for your users.

**Comment by youtux** [comment]
Sure thing, although I want to fix #16 before completing the transition.

**Comment by MikeMcQuaid** [comment]
@youtux Sure. I don't think it's necessary to finish first, personally, but if it's relatively straightforward: go for it.

**Comment by youtux** [comment]
Agreed, I don't have the time currently to fix it.

**Comment by MikeMcQuaid** [comment]
@youtux I've invited you to a team in the Homebrew organisation so you should be able to move this repository there now (let me know if you cannot). Let me know when/if you've done that and I'll make sure everything is setup properly. If you want me to add other maintainers as admins, I'll do that too. Thanks again!

**Comment by ilovezfs** [comment]
I think this actually is nice as it is now with the command and the Livecheckables in this separate repo because

- it keeps non-user-friendly and unsightly regex out of the formula files
- it avoids adding a formula component that is subject to inevitable breakage that is out of our control
- it allows us to freely tweak the command internals without the formality of Homebrew/brew, while still maintaining consistency amongst the maintainers using it
- it doesn't encourage users to open PRs based on guesses

**Comment by MikeMcQuaid** [comment]
Ok, seems fair enough to me, thanks @ilovezfs.
