### ISSUE TITLE
Avoid checking for older versions

### ISSUE THREAD

**Issue by miguelarauj1o** [Homebrew/homebrew-livecheck#17]
Running `brew livecheck` inside **homebrew-core/Formula** I get this:

``` shell
[...]
autoconf : 2.69 ==> 2.69
autoconf@2.13 (guessed) : 2.13 ==> 2.69
autoconf@2.64 (guessed) : 2.64 ==> 2.69
[...]
```

Since Homebrew provides official [support for different versions](https://brew.sh/2017/05/01/homebrew-1.2.0/), livecheck must adapt to the new changes in Homebrew. Perhaps detecting `@` in formula name.

I believe we need fix this before #16 happens.

**Comment by youtux** [comment]
I'll try to give it a look tonight, but if you have any suggestion it would be appreciated.

**Comment by ilovezfs** [comment]
For what it's worth, this is not a new problem. The exact same bogus upgrades have always been suggested. The formulae just had different names and were in homebrew/versions.
