### ISSUE TITLE
brew livecheck fobis errors

### ISSUE THREAD

**Issue by zbeekman** [Homebrew/homebrew-livecheck#23]
TBH I don't completely follow all the recent changes to Homebrew python formulae, but I did notice that the following command fails:

```
brew livecheck fobis
Error: Unable to get versions for Formulary::FormulaNamespacef73a16be95623ffceb9840d1317cb3d0::Fobis
```

Any thoughts on how to fix this? Is it a problem in the formula for `FoBiS` (in which case I can try taking a stab at fixing it) or is it a problem with livecheck?

Thanks!

**Comment by youtux** [comment]
Livecheck has some heuristics to get the latest version for some project. It seems that the latest version for FoBiS cannot be automatically detected. You can help fixing this by creating a `Livecheckables/fobis.rb` file with the right strategy to get the version.

**Comment by ilovezfs** [comment]
This is now fixed:
```
Josephs-MacBook-Pro:bfpr joe$ brew livecheck fobis
fobis (guessed) : 2.2.7 ==> 2.2.7
```
