### ISSUE TITLE
Livecheck errors for some formulae

### ISSUE THREAD

**Issue by nandahkrishna** [Homebrew/homebrew-livecheck#236]
On running `brew livecheck --all`, I noticed that an error message is thrown for some Formulae, such as `aamath`, `lrzip`, etc.

As pointed out by @dawidd6, the issue seems to be arising from the fact that these projects aren't hosted on well-known sites like GitHub. For example, as per homebrew-core, `lrzip` is hosted on the personal website of the developer.

Would fixes in the form of explicit Livecheckables be welcome for these formulae? Just confirming before I make PR(s) for these.

**Comment by dawidd6** [comment]
I say, yes.

**Comment by nandahkrishna** [comment]
Thanks for the quick response. I'll get on with this.

**Comment by samford** [comment]
Following up on this, we're aware that there are quite a number of formulae with errors or incorrect version matches. Activity around `livecheck` has picked up a bit lately, so it's improving little by little but there are no shortage of broken/incorrect `livecheck` results that need to be addressed.

If the formula is using the default `livecheck` heuristic but isn't properly matching the version, we can use a livecheckable to provide working behavior by:

A) Adding a regex to use in identifying version numbers
B) Adding a URL (i.e., a page to scrape or a Git repository to check tags (using `git ls-remote --tags`))
C) Adding a regex _and_ a URL

Note that it isn't always necessary to provide both a URL and a regex and sometimes you only need one or the other. It's best to provide only the minimal changes necessary to fix the issue.

For anyone who stumbles across this issue in the future, you can find additional advice in [my comment in the `aamath` PR](https://github.com/Homebrew/homebrew-livecheck/pull/238#issuecomment-590124809). I may use this as the basis for some better documentation for new contributors in the future but it's there for the time being.

Thanks for taking the time to help with `livecheck`!
