### ISSUE TITLE
Error: Version value must be a string: got a TrueClass (true)

### ISSUE THREAD

**Issue by samford** [Homebrew/homebrew-livecheck#250]
The recent changes to `heuristic.rb` in [91fd45a](https://github.com/Homebrew/homebrew-livecheck/commit/91fd45a055559441956f80b164af6078cf2d3fa6) introduced an error for some formulae (e.g., coreutils).

```
Error: coreutils: Version value must be a string; got a TrueClass (true)
```

I haven't had a chance to look into it yet, other than confirming it does not happen in the commit immediately preceding this one.

**Comment by dawidd6** [comment]
Sorry about that.

This commit should fix it: https://github.com/Homebrew/homebrew-livecheck/commit/c293de0d4c5079530966d6fb7b0d03cd5db91df3
