### ISSUE TITLE
livecheck does not report the previous failed attempts

### ISSUE THREAD

**Issue by chenrui333** [Homebrew/homebrew-livecheck#268]
Currently livecheck command does not report the previously failed attempts. It would be nice to report it out.

**Comment by samford** [comment]
I'm not totally sure that I understand what "failed attempts" is referring to here. Do you mean previous failed attempts at upgrading the formula (i.e., a PR that was opened for the version but closed without merging)?

If so, I definitely agree that something like this is needed to help prevent people from opening PRs for formulae that would just waste CI resources and maintainer time. We recently had someone go on a tear with `brew bump-formula-pr` in homebrew-core and, just from a quick glance, a number of the PRs are for formulae that haven't been upgraded yet _for a reason_. It's not uncommon for folks to not do enough due diligence before bumping a formula, so I've been wanting to make this information more accessible in various fashions.

As with #267, the forthcoming idea that I hinted at in [my comment to that issue](https://github.com/Homebrew/homebrew-livecheck/issues/267#issuecomment-593164251) would provide the information in this PR as well. The resulting setup would allow us to keep livecheck simple (compared to handling all this in livecheck itself), so I feel that it would be better to hold off on working on this at the moment.

I'll try to work on fleshing out my idea into a proposal in the not-too-distant future, as it contains a number of features that would make maintainers' (and contributors') lives easier and seeing these issues pop up just reinforces the idea for me. I appreciate your patience in the interim time.

**Comment by chenrui333** [comment]
> I'm not totally sure that I understand what "failed attempts" is referring to here. Do you mean previous failed attempts at upgrading the formula (i.e., a PR that was opened for the version but closed without merging)?

Yeah, exactly. Checking with the previous closed PRs (along with `build failure` or `test failure`).

> If so, I definitely agree that something like this is needed, to help prevent people from opening PRs for formulae that would just waste CI resources and maintainer time.

That sometimes includes me as well, not looking back for the closed PRs.

**Comment by MikeMcQuaid** [comment]
Closing for now but can be moved or reopened in Homebrew/brew if it applies to the new `brew livecheck` there.
