### ISSUE TITLE
dbus livecheck issue

### ISSUE THREAD

**Issue by chenrui333** [Homebrew/homebrew-livecheck#461]
dbus has already been upgraded to v1.13.12 (https://github.com/Homebrew/homebrew-core/pull/41925). but it still shows upgradeable. 

```
$ brew livecheck dbus
dbus (guessed) : 1.12.16 ==> 1.13.12
```

**Comment by Moisan** [comment]
`dbus` was not updated:
```
➜ brew info dbus
dbus: stable 1.12.16 (bottled), HEAD
```
Note the comment from fxcoudert:
> From wiki.freedesktop.org/www/Software/dbus/#index5h1
The current stable branch is dbus 1.12.x
Please make sure to only submit stable/release branche updates.

**Comment by chenrui333** [comment]
oh, sorry, I thought it was upgraded. Thanks for clarifying it!
