### ISSUE TITLE
cataclysm livecheck issue

### ISSUE THREAD

**Issue by chenrui333** [Homebrew/homebrew-livecheck#510]
The version schema is alphabetical instead of pure numeric.

0.9 is older than 0.E

debug log as below
```
0.1 => #<Version:0x00007fca6d2877a8 @version="0.1", @tokens=[#<Version::NumericToken 0>, #<Version::NumericToken 1>]>
0.2 => #<Version:0x00007fca6d287640 @version="0.2", @tokens=[#<Version::NumericToken 0>, #<Version::NumericToken 2>]>
0.3 => #<Version:0x00007fca6d287460 @version="0.3", @tokens=[#<Version::NumericToken 0>, #<Version::NumericToken 3>]>
0.4 => #<Version:0x00007fca6d2872f8 @version="0.4", @tokens=[#<Version::NumericToken 0>, #<Version::NumericToken 4>]>
0.5 => #<Version:0x00007fca6d287190 @version="0.5", @tokens=[#<Version::NumericToken 0>, #<Version::NumericToken 5>]>
0.6 => #<Version:0x00007fca6d287000 @version="0.6", @tokens=[#<Version::NumericToken 0>, #<Version::NumericToken 6>]>
0.7 => #<Version:0x00007fca6d286e20 @version="0.7", @tokens=[#<Version::NumericToken 0>, #<Version::NumericToken 7>]>
0.7.1 => #<Version:0x00007fca6d286c90 @version="0.7.1", @tokens=[#<Version::NumericToken 0>, #<Version::NumericToken 7>, #<Version::NumericToken 1>]>
0.8 => #<Version:0x00007fca6d286b28 @version="0.8", @tokens=[#<Version::NumericToken 0>, #<Version::NumericToken 8>]>
0.9 => #<Version:0x00007fca6d286970 @version="0.9", @tokens=[#<Version::NumericToken 0>, #<Version::NumericToken 9>]>
0.A => #<Version:0x00007fca6d286808 @version="0.A", @tokens=[#<Version::NumericToken 0>, #<Version::StringToken "A">]>
0.B => #<Version:0x00007fca6d2866a0 @version="0.B", @tokens=[#<Version::NumericToken 0>, #<Version::StringToken "B">]>
0.C => #<Version:0x00007fca6d286538 @version="0.C", @tokens=[#<Version::NumericToken 0>, #<Version::StringToken "C">]>
0.D => #<Version:0x00007fca6d2863a8 @version="0.D", @tokens=[#<Version::NumericToken 0>, #<Version::StringToken "D">]>
0.E => #<Version:0x00007fca6d286218 @version="0.E", @tokens=[#<Version::NumericToken 0>, #<Version::StringToken "E">]>
cataclysm : 0.E ==> 0.9
```

**Comment by samford** [comment]
I've already come across this issue with the `cataclysm` formula, investigated the problem, and tested out fixes. Basically, this is related to how `Version` tokens are compared and to fix this we have to treat letters as newer than numbers. However, this is more complicated than it sounds and making that change currently breaks a lot of checks, as seen in: Homebrew/brew#7181

I intend to follow up on my initial attempts at resolving this issue but it won't be for quite a while. I imagine I'll need to make quite a number of changes to formulae checks before being able to make the aforementioned change in Homebrew/brew without breaking anything.

**Comment by samford** [comment]
I updated the `cataclysm` livecheckable in #811 to avoid this issue (checking the "latest" release on GitHub), so livecheck now returns the correct latest version.

I made a note on my to-do list to revisit the underlying version comparison issue in the future (once livecheck is working for almost all formulae) but I think we can close this issue now.
