### ISSUE TITLE
libxml++ livecheck issue

### ISSUE THREAD

**Issue by chenrui333** [Homebrew/homebrew-livecheck#537]
Currently, `libxml++` should follow 2.40 line instead of also checking against libxml++ 3.x

### current behavior
```
libxml++ (guessed) : 2.40.1 ==> 3.2.0
```

### desired
```
libxml++ : 2.40.1 ==> 2.40.1
```

**Comment by samford** [comment]
This is one of the formulae that I intend to address after #536 is merged. I compiled a list of formulae like these in the past which encompasses all of the formulae you've already mentioned in PRs or issues related to version restriction, so rest assured they'll be addressed in due time.
