### ISSUE TITLE
List of versioned formula does not check against the new versions

### ISSUE THREAD

**Issue by chenrui333** [Homebrew/homebrew-livecheck#548]
Right now, if there is no matched livecheckable with the versioned formula, there would be no version report on the versioned formula. Instead, it would just report as `xx@x.x : versioned` (for example, `ansible@2.8 : versioned`).

### Expected

Versioned formula should be checked against as well.

### List of unchecked versioned formulae

* [ ] `ansible@2.8`
* [ ] `antlr@2`
* [ ] `autoconf@2.13`
* [ ] `awscli@1`
* [ ] `berkeley-db@4`
* [ ] `bison@2.7`
* [ ] `boost@1.55`
* [ ] `boost@1.57`
* [ ] `boost@1.59`
* [ ] `boost@1.60`
* [ ] `cassandra@2.1`
* [ ] `cassandra@2.2`
* [ ] `elasticsearch@2.4`
* [ ] `erlang@21`
* [ ] `gcc@8`
* [ ] `ghc@8.6`
* [ ] `gmt@5`
* [ ] `gnuplot@4`
* [ ] `go@1.11`
* [ ] `go@1.12`
* [ ] `go@1.13`
* [ ] `hdf5@1.10`
* [ ] `helm@2`
* [ ] `libsigc++@2`
* [ ] `libtensorflow@1`
* [ ] `llvm@6`
* [ ] `llvm@7`
* [ ] `llvm@8`
* [ ] `llvm@9`
* [ ] `lua@5.1`
* [ ] `mariadb@10.3`
* [ ] `maven@3.2`
* [ ] `maven@3.3`
* [ ] `maven@3.5`
* [ ] `mysql-client@5.7`
* [ ] `mysql-connector-c++@1.1`
* [ ] `numpy@1.16`
* [ ] `opencv@3`
* [ ] `openjdk@11`
* [ ] `php@7.2`
* [ ] `php@7.3`
* [ ] `postgresql@10`
* [ ] `postgresql@11`
* [ ] `protobuf@3.6`
* [ ] `protobuf@3.7`
* [ ] `python@3.8`
* [ ] `redis@4.0`
* [ ] `ruby@2.4`
* [ ] `ruby@2.5`
* [ ] `ruby@2.6`
* [ ] `sbt@0.13`
* [ ] `scala@2.11`
* [ ] `scala@2.12`
* [ ] `solr@7.7`
* [ ] `subversion@1.8`
* [ ] `swagger-codegen@2`
* [ ] `swig@3`
* [ ] `terraform@0.11`
* [ ] `thrift@0.9`
* [x] `traefik@1`
* [ ] `v8@3.15`

**Comment by samford** [comment]
Some versioned formulae will never see a new release, so we should make sure that it's actually beneficial to check for a new version before adding a livecheckable.

It's also worth mentioning that some formulae are versioned without using the `@` naming convention, like GNOME formulae that follow a convention where `formulaname` is for versions with a major of 2, `formulaname3` is for versions with a major of 3, etc.

**Comment by samford** [comment]
I'm doing a bit of tidying with the impending migrations in mind. It's very easy to generate this list of versioned formulae and I don't want to drive contributors to work on these right now, so I'm going to go ahead and close this. We can revisit this sometime in the future when it's more appropriate to work on.
