### ISSUE TITLE
mafft livecheck did not consider `experimental` release

### ISSUE THREAD

**Issue by chenrui333** [Homebrew/homebrew-livecheck#558]
The latest release `v7.464` was marked as experimental release, but currently the `brew livecheck` did not consider that flag.

```
$ brew livecheck mafft
mafft : 7.453 ==> 7.464
```

relates to https://github.com/Homebrew/homebrew-core/pull/53706

**Comment by samford** [comment]
Hm, what a peculiar situation. The homepage currently says:

"The latest version is 7.450, 2019/Nov.

An experimental version, 7.464, supports full-length MSA of closely-related viral geonmes.   New!  (2020/Apr/21)

BUG!! Version 7.463 had a bug.  Please update 7.463 to 7.464.  (2020/Apr/21)"

Before November 2019, the homepage said "The latest version is 7.429 (Windows), 7.427 (others), 2019/Jun.", so it doesn't seem like that text is something reliable to match against.

Additionally, the [Source](https://mafft.cbrc.jp/alignment/software/source.html) page lists 7.464 as experimental but 7.453 is also listed without the "Experimental" text next to it. The source page seemingly indicates that the latest version is 7.453 but the home page says 7.450.

Seeing as the latest version in the `mafft` formula is 7.453 and there wasn't any complaints about it being experimental (the WayBack Machine doesn't have snapshots of the source page where we could see if it was ever experimental), I think we can just restrict the regex in the livecheckable to only match the non-experimental version.

I'll create a PR that closes this issue in a little bit.
