### ISSUE TITLE
bash livecheck issue

### ISSUE THREAD

**Issue by miccal** [Homebrew/homebrew-livecheck#806]
In the last day or two I have noticed that `brew livecheck bash` is not working:
```
-bash-5.0.17- /Users/miccal (28) [> brew livecheck bash
Error: bash: Unable to get versions
```
The `livecheckable` for `bash` is copied below:
```
class Bash
  livecheck do
    url "http://ravenports.ironwolf.systems/catalog/bucket_C8/bash/standard/"
    regex(%r{<td id="pkgversion">([0-9.]+)</td>})
  end
end
```
Now, initially I assumed that it may have something to to with the site `http://ravenports.ironwolf.systems/catalog/bucket_C8/bash/standard/`, but checking the source I find that
```
<td id="pkgversion">5.0.17_1</td>
```
as expected. 

Now, I have attempted to update the regex and rectify this myself, but no matter what I try I get the same error as above. Since there is a lot going on behind-the-scenes in the `homebrew-livecheck` repository at present, I thought that perhaps _something_ has changed in the underlying code of `livecheck` to cause this issue, as I am at a loss to explain the failure.

Thank you.

**Comment by SMillerDev** [comment]
@nandahkrishna got any idea?

**Comment by nandahkrishna** [comment]
Checking this. I don't remember changing any of the matching logic myself though.

**Comment by nandahkrishna** [comment]
Well so looking at the regex, it doesn't match the current livecheck standard. So that has to be updated. Also, it's not designed to match the underscores. That's probably the issue with this one.

**Comment by miccal** [comment]
@nandahkrishna but I don't think you would _want_ to match the `_1` part, would you not want to just match the `5.0.17`?

**Comment by nandahkrishna** [comment]
Yeah we shouldn't match the `_1`. Do you know if the website was recently updated, maybe earlier it was just `5.0.17` but now they changed it to `5.0.17_1`?

Anyways the fix is simple.

```ruby
class Bash
  livecheck do
    url "http://ravenports.ironwolf.systems/catalog/bucket_C8/bash/standard/"
    regex(%r{<td id="pkgversion">([0-9.]+)(?:_[0-9]+)?</td>})
  end
end
```

Just move the suffix matching outside the capturing group. We could also go ahead and make sure this regex meets our current standards.

```ruby
class Bash
  livecheck do
    url "http://ravenports.ironwolf.systems/catalog/bucket_C8/bash/standard/"
    regex(%r{<td id="pkgversion">v?(\d+(?:\.\d+)+)(?:_\d+)?</td>})
  end
end
```

This gives you the output:
```
bash : 5.0.17 ==> 5.0.17
```

Does that work @miccal?

**Comment by miccal** [comment]
Perfect, thank you @nandahkrishna -- would you like to send through an update, or shall I?

**Comment by nandahkrishna** [comment]
Feel free to open the PR @miccal!

**Comment by miccal** [comment]
@nandahkrishna I looked also, but it is not easy for `bash` as it is version `5.0` (at http://ftp.gnu.org/gnu/bash/) and patch `17` (inside a folder called `bash-5.0-patches`).

**Comment by nandahkrishna** [comment]
Yeah that's all I found too. It's not possible for us to work with that (I think), so what we arrived at earlier is the best possible solution.

**Comment by miccal** [comment]
https://github.com/Homebrew/homebrew-livecheck/pull/807
