### ISSUE TITLE
gst 1.17 unstable releases

### ISSUE THREAD

**Issue by chenrui333** [Homebrew/homebrew-livecheck#999]
Currently the gst formulae shown as version bump needed, but the [1.17 series](https://gstreamer.freedesktop.org/) are unstable releases and should be ignored.
```
gst-plugins-bad : 1.16.2 ==> 1.17.1
gst-plugins-base : 1.16.2 ==> 1.17.1
gst-plugins-good : 1.16.2 ==> 1.17.1
gst-plugins-ugly : 1.16.2 ==> 1.17.1
gst-validate (guessed) : 1.16.2 ==> 1.17.1
gstreamer : 1.16.2 ==> 1.17.1
```

**Comment by nandahkrishna** [comment]
Thanks for pointing this out @chenrui333. We avoided this issue thanks to @samford pointing it out for `gat-python`, and should fix it in these formulae's Livecheckables as well.

**Comment by samford** [comment]
Thanks @nandahkrishna for fixing these issues and @chenrui333 for bringing this up.
